baseURL = 'https://anzuchitakuro.github.io/takuroblog/'
title = 'Takuro Blog'
theme = "hugo-theme-cleanwhite"
languageCode = 'ja'
# Enable comments by entering your Disqus shortname
disqusShortname = ""
googleAnalytics = ""
preserveTaxonomyNames = true
paginate = 5 #frontpage pagination
hasCJKLanguage = true

[outputs]
home = ["HTML", "RSS"]

[params]
header_image = "img/home-bg-jeep.jpg"
SEOTitle = "Takuro Blog"
description = "Takuro's Blog. About android developer, career, lifestyle."
keyword = "android, kotlin, career, lifestyle"
slogan = ""

image_404 = "img/404-bg.jpg"
title_404 = "Page Not Found :("
omit_categories = false

# leancloud storage for page view counter
page_view_conter = false
leancloud_app_id = ""
leancloud_app_key = ""

# algolia site search
algolia_search = true
algolia_appId = ""
algolia_indexName = ""
algolia_apiKey = ""

# Sidebar settings
sidebar_about_description = "android developer"
sidebar_avatar = ""
featured_tags = true
featured_condition_size = 1

# Baidu Analytics
ba_track_id = ""
disqus_proxy = ""
disqus_site = ""
twikoo_env_id = ""
reward = true
friends = false
bookmarks = false
about_me = true

[params.social]
rss            = true
github         = "https://github.com/anzuchitakuro"

[[params.addtional_menus]]
title =  "ABOUT"
href =  "/takuroblog/about/"

[markup]
[markup.tableOfContents]
endLevel = 2
startLevel = 1
[markup.highlight]
style = "dracula"
